projects:
  Development Salgssystem AppSync:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/graphql/API.ts
        docsFilePath: src/graphql
        region: eu-central-1
        apiId: j6b7e5f3knfxroys2ni7v4txwu
        maxDepth: 2
